### ISSUE TITLE
node error when using Dialog, svelte-mui@0.3.3-3, svelte@3.23.2

### ISSUE THREAD

**Issue by Termite** [vikignt/sapper-mui#1]
Hi,

when using the Dialog component as in the example ( <Dialog visible>...</Dialog>)
I get the following exceptions from node:
(node:30393) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'querySelectorAll' of undefined
    at onVisible (/home/micha/svelte-app/motor-racing/__sapper__/dev/server/server.js:1128:20)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:30393) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:30393) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:30393) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'querySelectorAll' of undefined
    at onVisible (/home/micha/svelte-app/motor-racing/__sapper__/dev/server/server.js:1128:20)
(node:30393) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)

What can cause this?

Thanks for helping
 Michael

**Comment by vikignt** [comment]
Hi @Termite,
this error can happen in the sapper application if a page with a visible by default dialog is loaded. I fixed it in version 0.3.3-4, try it, and if you have any problems let me know.

**Comment by Termite** [comment]
Cool, you fixed it, it works now. Thanks for doing it so fast.

Cheers,
 Michael
